server:
  port: 8080

spring:
  application:
    name: nexon-platform-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/nexon_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: nexon1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate # 어제 DDL로 테이블을 이미 생성했으므로 스키마 일치 여부만 검증
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379